/**:
    ros__parameters:
        map_file_path: "./test.pcd"
        feature_extract_enable: false
        filter_size_map: 0.1
        filter_size_surf: 0.1
        radius_filter_map: 0.02
        
        
        common:
            lid_topic:  "/livox/lidar"
            imu_topic:  "/livox/imu"
            time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

        preprocess:
            lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for any other pointcloud input
            scan_line:  4
            blind: 0.5
            timestamp_unit: 3
            scan_rate: 10

        mapping:
            acc_cov: 0.1 #加速度协方差
            gyr_cov: 0.1 # 陀螺仪协方差
            b_acc_cov: 0.0001 # 加速度计偏差
            b_gyr_cov: 0.0001 # 陀螺仪偏差 
            fov_degree:    360.0 # 视场角
            det_range:     260.0 #检测范围
            extrinsic_est_en: true      # true: enable the online estimation of IMU-LiDAR extrinsic
            #  参数代表 IMU 和 LiDAR 之间外参校准的平移向量和旋转矩阵。
            extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
            extrinsic_R: [ 0.9999161, 0.0026676,  0.0126707,
            		 -0.0025826, 0.9999741, -0.0067201,
            		 -0.0126883, 0.0066868,  0.9998971]
            # 系统的初始平移向量和旋转矩阵。
            init_T: [ 0.298375, -0.00120827, 0.131974 ]
            init_R: [ 0.460357,    0.459737,    0.758802,
             	 -0.705492,    0.708506,  -0.0012503, 
             	 -0.538575,   -0.535138,    0.651286]

        publish:
            path_en: true                # true: publish Path
            effect_map_en: false         # true: publish Effects
            map_en: false                 # true: publish Map cloud
            scan_publish_en: true       # false: close all the point cloud output
            dense_publish_en: true      # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
            filter_map_enable: true
            
        pcd_save:
            pcd_save_en: false
            interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

        erasor: 
            max_range: 80.0
            num_rings: 20
            num_sectors: 108
            min_h: -1.8 # [m] Note that it depends on the distance between body frame and ground contact point of mobile robots
            max_h: 1.5 # [m] Note that it depends on the distance between body frame and ground contact point of mobile robots
            scan_ratio_threshold: 0.20 # The Larger, the more aggressive!!
            minimum_num_pts: 6

            gf_dist_thr: 0.125
            gf_iter: 3
            gf_num_lpr: 10
            gf_th_seeds_height: 0.5
            num_lowest_pts: 1

        MapUpdater:
            query_voxel_size: 0.02
            map_voxel_size: 0.02
            voxelization_interval: 10
            removal_interval: 5

        tf:
            lidar2body: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0] # xyz q_x, q_y, q_z, q_w in order
        
        verbose: false # debug print log etc

        Octomap:
            resolution: 0.1

            maxRange: -1.0
            minRange: -1.0

            probHit: 0.7
            probMiss: 0.4
            thresMin: 0.12
            thresMax: 0.97

            opccupancyThres: 0.7

            m_prune: true

            filterGroundPlane: false

            m_groundFilterDistance: 0.04
            m_groundFilterAngle: 0.15
            m_groundFilterPlaneDistance: 0.15

            filterNoise: true

            filterMeanK: 50
            StddevMulThresh: 1.0

        publishmap:
            size: 0.02
            publish_map_en: true
        
        segment:
            segment_en: true
            publish_map_en: true

        PCA:
            publish_map_en: true
        
        cloudcompare:
            resolution: 0.1
            radius: 0.05
            clusterTolerance: 0.1
            minClusterSize: 10
            maxClusterSize: 200





