/**:
    ros__parameters:
        map_file_path: "./test.pcd"
        feature_extract_enable: false
        filter_size_map: 0.05
        filter_size_surf: 0.05
        filter_radius_filter_map: 0.15
        radius_filter_map: 0.1
        
        
        common:
            lid_topic:  "/livox/lidar"
            imu_topic:  "/livox/imu"
            time_sync_en: false         # ONLY turn on when external time synchronization is really not possible
            time_offset_lidar_to_imu: 0.0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                        # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

        preprocess:
            lidar_type: 1                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for any other pointcloud input
            scan_line:  4
            blind: 0.5
            timestamp_unit: 3
            scan_rate: 10

        mapping:
            acc_cov: 0.1 #加速度协方差
            gyr_cov: 0.1 # 陀螺仪协方差
            b_acc_cov: 0.0001 # 加速度计偏差
            b_gyr_cov: 0.0001 # 陀螺仪偏差 
            fov_degree:    360.0 # 视场角
            det_range:     260.0 #检测范围
            extrinsic_est_en: true      # true: enable the online estimation of IMU-LiDAR extrinsic
            #  参数代表 IMU 和 LiDAR 之间外参校准的平移向量和旋转矩阵。
            extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
            extrinsic_R: [ 0.9999161, 0.0026676,  0.0126707,
            		 -0.0025826, 0.9999741, -0.0067201,
            		 -0.0126883, 0.0066868,  0.9998971]
            # 系统的初始平移向量和旋转矩阵。
            init_T: [ 0.298375, -0.00120827, 0.131974 ]
            init_R: [ 0.460357,    0.459737,    0.758802,
             	 -0.705492,    0.708506,  -0.0012503, 
             	 -0.538575,   -0.535138,    0.651286]
                 

        publish:
            path_en: true                # true: publish Path
            effect_map_en: false         # true: publish Effects
            map_en: false                 # true: publish Map cloud
            scan_publish_en: true       # false: close all the point cloud output
            dense_publish_en: true      # false: low down the points number in a global-frame point clouds scan.
            scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
            filter_map_enable: true
            
        pcd_save:
            pcd_save_en: true
            interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
